# Generated by Django 3.2 on 2021-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecontent',
            name='original_content',
            field=models.CharField(default='', max_length=200),
        ),
    ]
