# Generated by Django 3.2 on 2021-05-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0002_packagecontent_original_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surcharge',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='ryczalt',
        ),
        migrations.AddField(
            model_name='surcharge',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
