# Generated by Django 3.2 on 2021-05-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0004_auto_20210529_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesubstance',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
