# Generated by Django 3.2 on 2021-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0005_alter_activesubstance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedose',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='packagecontent',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
